### ISSUE TITLE
remove cilium ingress controller legacy code

### ISSUE THREAD

**Issue by sebiklamar** [isejalabs/terraform-proxmox-talos#78]
Remove legacy code for cilium `ingressController` as it's disabled and, hence, not used

```yaml
# k8s/core/network/cilium/<env>/values.yaml / additional-values.yaml
ingressController:
  enabled: false
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.223
```
